Repository Team-Motivoo/Motivoo-iOS, pull requests merged in 2024-03, with the labels that each got.

#76 [Chore] #75 - 디자인 시스템 컬러 수정
  Motivoo-iOS/Motivoo-iOS/Global/Extension/UIColor+.swift
Labels: Chore 📢

#77 [Refactor] #72 홈 API 수정사항 반영 및 미션선택 버그 해결
  Motivoo-iOS/Motivoo-iOS.xcodeproj/project.pbxproj
  Motivoo-iOS/Motivoo-iOS/Data/Home/APIModel/HomeMissionCheckResponse.swift
  Motivoo-iOS/Motivoo-iOS/Data/Home/APIModel/HomePatchMission.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/ViewControllers/HomeProveSuccessViewController.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/ViewControllers/HomeViewController.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/Views/Main/HomeMissionView.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/Views/Main/HomeView.swift
  Motivoo-iOS/Motivoo-iOS/Global/Literals/URLs.swift
  Motivoo-iOS/Motivoo-iOS/Network/Home/HomeAPI.swift
  Motivoo-iOS/Motivoo-iOS/Network/Home/HomeService.swift
Labels: Refactor 🎨

#80 [Refactor] #72 - HomeAPI Network파일 수정사항
  Motivoo-iOS/Motivoo-iOS/Network/Home/HomeAPI.swift
  Motivoo-iOS/Motivoo-iOS/Network/Home/HomeService.swift
Labels: Refactor 🎨

#85 [Fix] #83 - 온보딩 모티부 시작하기 버튼 활성화 수정
  Motivoo-iOS/Motivoo-iOS/Feature/Onboarding/ViewControllers/OnboardingViewController.swift
Labels: Fix 🛠️

#86 [Feat] #81 2차 스프린트 UI, 기획 수정사항 반영
  Motivoo-iOS/Motivoo-iOS/Feature/Home/ViewControllers/HomeViewController.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/Views/Main/HomeCircularProgressView.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/Views/Main/HomeStepCountView.swift
  Motivoo-iOS/Motivoo-iOS/Feature/Home/Views/Main/HomeView.swift
  Motivoo-iOS/Motivoo-iOS/Feature/MyPage/ViewControllers/MyPageViewController.swift
  Motivoo-iOS/Motivoo-iOS/Feature/MyPage/Views/DisclosureTableViewCell.swift
  Motivoo-iOS/Motivoo-iOS/Feature/MyPage/Views/MyPageView.swift
  Motivoo-iOS/Motivoo-iOS/Global/Literals/TextLiterals.swift
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/check_active.imageset/Contents.json
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/check_active.imageset/checkbox_secondary_active.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/child.imageset/Contents.json
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/child.imageset/Frame 1000011879.png
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/child.imageset/Frame 1000011879@2x.png
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/child.imageset/Frame 1000011879@3x.png
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/child.imageset/profile.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/img_home_mission_complete.imageset/Contents.json
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/img_home_mission_complete.imageset/img_home_after.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/img_home_mission_complete.imageset/img_home_mission_complete.png
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/img_home_mission_complete.imageset/img_home_mission_complete@2x.png
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/img_home_mission_complete.imageset/img_home_mission_complete@3x.png
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/mission_main.imageset/Contents.json
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/mission_main.imageset/img_home.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/mission_main.imageset/img_home_before.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/shoes.imageset/Contents.json
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/shoes.imageset/icon_exercise.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/shoes.imageset/icon_exercise@2x.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Assets.xcassets/shoes.imageset/icon_exercise@3x.svg
  Motivoo-iOS/Motivoo-iOS/Global/Resources/Info.plist
  Motivoo-iOS/Motivoo-iOS/Global/SupportingFiles/StepCountManager.swift
Labels: Feat🪄
